<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="TU">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Employee">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Post" type="xs:string"/>
              <xs:element name="Salary" type="xs:integer"/>
              <xs:element name="Gender">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="male"/>
                    <xs:enumeration value="female"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="UserName">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[a-zA-Z]{5,10}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Password">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[A-Z][a-z][0-9][@#$].{2,5}"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

